name: Sync selected JSON/TXT files to openrouter-free-ai-model-auto-update

on:
  push:
    branches:
      - main
    paths:
      - "ai-desc.json"
      - "ai.txt"
  schedule:
    # هر هفته یکشنبه ساعت 01:00 شب UTC
    - cron: '0 1 * * 0'

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Trigger PHP updater
        run: |
          curl -s https://www.intellsoft.ir/update/review/get_free_models.php
          sleep 240
          
      - name: Prepare files to sync
        run: |
          mkdir sync-output
          cp ai-desc.json sync-output/
          cp ai.txt sync-output/

      - name: Push selected files to target repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: 'sync-output'
          destination-github-username: 'intellsoft'
          destination-repository-name: 'openrouter-free-ai-model-auto-update'
          user-email: '${{ github.actor }}@users.noreply.github.com'
          target-branch: main
